alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ls='ls --color=auto -A'
alias tree='tree -C'
alias diff='diff --color=auto'
alias vim='vim -u ~/.vim/vimrc'
alias config='git --git-dir $HOME/.dotfiles --work-tree $HOME'
