c run "/bin/bash" "-c" "echo \"${sub-text}\" | tr \"\\n\" \" \" |  xclip -selection clipboard"
X script-binding vtt/convert-vtt
F5 script-binding deepl/sub_ab_loop
C script-binding deepl/show-translation-deepl
