save-watch-history=yes
write-filename-in-watch-later-config=yes

vo=gpu
hwdec=vaapi
scale=bilinear
cscale=bilinear
tscale=oversample
scaler-resizes-only=yes
deband=no
interpolation=no
correct-downscaling=no
