#!/bin/sh

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi


# Source xprofile
source "$XDG_CONFIG_HOME/X11/xprofile"


# Here bspwm is kept as default
session=${1:-bspwm}

case $session in
bspwm)
	exec bspwm
	;;
i3)
	exec i3
	;;
dwm)
	exec dwm
	;;
emacs)
	exec emacs
	;;
*)
	exec $1
	;;
esac
