#!/bin/sh

# merge in defaults and keymaps
userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap
[[ -f $sysresources ]] && xrdb -merge $sysresources
[[ -f $sysmodmap ]] && xmodmap $sysmodmap
[[ -f $userresources ]] && xrdb -merge "$userresources"
[[ -f $usermodmap ]] && xmodmap "$usermodmap"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# Source xprofile
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ]; then
	source "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile"
else
	source "$HOME/.xprofile"
fi

exec i3
