#!/bin/sh

# merge in defaults and keymaps
userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap
[[ -f $sysresources ]]  && xrdb -merge $sysresources
[[ -f $sysmodmap ]]     && xmodmap $sysmodmap
[[ -f $userresources ]] && xrdb -merge "$userresources"
[[ -f $usermodmap ]]    && xmodmap "$usermodmap"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?* ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xset r rate 1000 5
xset -b
xset s 600 60
dunst &
redshift &
xss-lock -- i3lock -n &
setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl

command -v picom >/dev/null 2>&1 && picom --experimental-backends --daemon

session=${1:-i3}
case $session in
    i3|i3wm           ) exec i3;;
    openbox           ) exec openbox-session;;
    *                 ) exec $1;;
esac
