#!/bin/sh

# merge in defaults and keymaps
userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap
[[ -f $sysresources ]]  && xrdb -merge $sysresources
[[ -f $sysmodmap ]]     && xmodmap $sysmodmap
[[ -f $userresources ]] && xrdb -merge "$userresources"
[[ -f $usermodmap ]]    && xmodmap "$usermodmap"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?* ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xset r rate 600 15
[[ -d /usr/share/fonts/terminus ]] && xset +fp /usr/share/fonts/terminus
udiskie &
dunst &
redshift &
xset -b &
xset s 600 60
xss-lock -- i3lock -n &
setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl

xrandr --output VGA1 --auto
xrandr --output HDMI-0 --auto --right-of VGA1
xrandr --setmonitor SECONDARY "1280/364x720/208+0+0" VGA1
xrandr --setmonitor PRIMARY "1920/520x1080/290+1440+0" HDMI-0

command -v picom >/dev/null 2>&1 && picom --experimental-backends -b
command -v feh >/dev/null 2>&1 && feh --bg-scale /usr/share/backgrounds/archlinux/reflected.jpg

echo holaaa

session=${1:-i3}
case $session in
    i3|i3wm           ) exec i3;;
    openbox           ) exec openbox-session;;
    *                 ) exec $1;;
esac
