#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color '#444444'
bspc config normal_border_color  '#BBBBBB'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Matplotlib state=floating
bspc rule -a matplotlib state=floating
bspc rule -a R_x11 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a st-256color state=pseudo_tiled
bspc rule -a URxvt state=pseudo_tiled
bspc rule -a Zathura state=tiled
bspc rule -a qutebrowser locked=on

bspc rule -a Emacs state=floating sticky=on
