#!/usr/bin/env bash

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=("$prefix"/**/*.gpg)
password_files=("${password_files[@]#"$prefix"/}")
password_files=("${password_files[@]%.gpg}")
password=$(printf '%s\n' "${password_files[@]}" | dmenu)
[[ -n $password ]] || exit

command=$1
case $1 in
"-o")
	keys=$(pass otp "$password")
	echo fake-key \""$keys"\" >>$QUTE_FIFO
	;;
"-p")
	keys=$(pass show "$password" | {
		IFS= read -r pass
		printf %s "$pass"
	})
	echo fake-key \""$keys"\" >>$QUTE_FIFO
	;;
"-u")
	keys=$(basename "$password")
	echo fake-key \""$keys"\" >>$QUTE_FIFO
	;;
"-a")
	keys=$(basename "$password")
	echo fake-key \""$keys"\" >>$QUTE_FIFO
	echo fake-key "<TAB>" >>$QUTE_FIFO
	keys=$(pass show "$password" | {
		IFS= read -r pass
		printf %s "$pass"
	})
	echo fake-key \""$keys"\" >>$QUTE_FIFO
	;;
esac

echo mode-enter insert >>$QUTE_FIFO
